const fs = require('fs');
let c = fs.readFileSync('d:\\safe-neighborhood-watch-main11\\frontend_deploy\\src\\pages\\Auth.tsx', 'utf8');

c = c.replace(/className=\"pl-12 h-14 rounded-xl bg-\\[#f3fafd\\] border-2 border-\\[#217093\\] focus-visible:ring-0 focus-visible:border-\\[#4eb8dd\\] text-base font-semibold text-\\[#353538\\] transition-all\"/g, 'className="pl-12 h-14 rounded-2xl bg-muted/40 border border-border/50 hover:border-primary/50 hover:bg-muted/60 focus-visible:border-primary focus-visible:ring-4 focus-visible:ring-primary/20 focus-visible:bg-background text-base font-medium transition-all shadow-sm"');
c = c.replace(/className=\"pl-12 pr-14 h-14 rounded-xl bg-\\[#f3fafd\\] border-2 border-\\[#217093\\] focus-visible:ring-0 focus-visible:border-\\[#4eb8dd\\] text-base font-semibold text-\\[#353538\\] transition-all\"/g, 'className="pl-12 pr-14 h-14 rounded-2xl bg-muted/40 border border-border/50 hover:border-primary/50 hover:bg-muted/60 focus-visible:border-primary focus-visible:ring-4 focus-visible:ring-primary/20 focus-visible:bg-background text-base font-medium transition-all shadow-sm"');
c = c.replace(/text-\\[#217093\\] group-focus-within:text-\\[#4eb8dd\\]/g, 'text-muted-foreground group-focus-within:text-primary');
c = c.replace(/text-\\[#217093\\] group-focus-within:text-\\[4eb8dd\\]/g, 'text-muted-foreground group-focus-within:text-primary');
c = c.replace(/text-\\[#217093\\]/g, 'text-foreground/80');

// Fix button styling
c = c.replace(/className=\"w-full h-14 rounded-2xl font-black text-lg bg-primary hover:bg-primary\/90 text-white shadow-xl shadow-primary\/25 transition-all hover:scale-\\[1.02\\] active:scale-\\[0.98\\]\"/g, 'className="relative group w-full h-14 rounded-2xl font-black text-lg bg-gradient-to-r from-primary to-primary/80 hover:from-primary/90 hover:to-primary text-white shadow-xl shadow-primary/25 transition-all hover:scale-[1.02] active:scale-[0.98] overflow-hidden"');
c = c.replace(/className=\"w-full h-14 rounded-2xl font-black text-lg bg-primary hover:bg-primary\/90 text-white shadow-xl shadow-primary\/25 transition-all active:scale-\\[0.98\\]\"/g, 'className="relative group w-full h-14 rounded-2xl font-black text-lg bg-gradient-to-r from-primary to-primary/80 hover:from-primary/90 hover:to-primary text-white shadow-xl shadow-primary/25 transition-all hover:scale-[1.02] active:scale-[0.98] overflow-hidden"');
c = c.replace(/{loading \? \"Verifying\.\.\.\" : \"Verify Identity\"}/g, '<div className="absolute inset-0 w-full h-full bg-gradient-to-r from-transparent via-white/20 to-transparent -translate-x-full group-hover:animate-shimmer" />{loading ? "Verifying..." : "Verify Identity"}');
c = c.replace(/{loading \? <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1 }}><Sparkles className=\"h-5 w-5\" \/><\/motion.div> : \"Login to Account\"}/g, '<div className="absolute inset-0 w-full h-full bg-gradient-to-r from-transparent via-white/20 to-transparent -translate-x-full group-hover:animate-shimmer" />{loading ? <motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 1 }}><Sparkles className="h-5 w-5" /></motion.div> : "Login to Account"}');
c = c.replace(/{loading \? \"Creating Account\.\.\.\" : \"Create Free Account\"}/g, '<div className="absolute inset-0 w-full h-full bg-gradient-to-r from-transparent via-white/20 to-transparent -translate-x-full group-hover:animate-shimmer" />{loading ? "Creating Account..." : "Create Free Account"}');


// Fix Left Panel animation
c = c.replace(/<div className=\"absolute top-0 right-0 w-96 h-96 bg-white\/10 rounded-full -translate-y-1\/2 translate-x-1\/2 blur-3xl\"><\/div>/g, '<motion.div animate={{ scale: [1, 1.2, 1], rotate: [0, 90, 0] }} transition={{ duration: 20, repeat: Infinity, ease: "linear" }} className="absolute top-0 right-0 w-[40rem] h-[40rem] bg-gradient-to-br from-white/20 to-transparent rounded-full -translate-y-1/2 translate-x-1/4 blur-3xl pointer-events-none"></motion.div>');
c = c.replace(/<div className=\"absolute bottom-0 left-0 w-64 h-64 bg-black\/20 rounded-full translate-y-1\/2 -translate-x-1\/2 blur-2xl\"><\/div>/g, '<motion.div animate={{ scale: [1, 1.5, 1], rotate: [0, -90, 0] }} transition={{ duration: 25, repeat: Infinity, ease: "linear" }} className="absolute bottom-0 left-0 w-[30rem] h-[30rem] bg-gradient-to-tr from-black/30 to-transparent rounded-full translate-y-1/3 -translate-x-1/4 blur-3xl pointer-events-none"></motion.div>');

fs.writeFileSync('d:\\safe-neighborhood-watch-main11\\frontend_deploy\\src\\pages\\Auth.tsx', c);
